name: films_hub
description: A Flutter project for Flutter-developer course by MadBrains.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.0.13

  drift: ^1.5.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0

  equatable: 2.0.3
  flutter_bloc: ^8.0.1

  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0

  json_annotation: 4.4.0

  dio: ^4.0.4
  pretty_dio_logger: ^1.1.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  dart_style: 2.2.1

  drift_dev: ^1.5.2

  test: ^1.21.0
  build_runner: 2.1.7
  json_serializable: 6.1.3

  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/images/poster-placeholder.jpg
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-VariableFont_wght.ttf

  uses-material-design: true