name: films_hub
description: A Flutter project for Flutter-developer course by MadBrains.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  test: ^1.21.0


  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/images/poster-placeholder.jpg
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-VariableFont_wght.ttf

  uses-material-design: true